apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 159960117927.dkr.ecr.ap-northeast-2.amazonaws.com/
  newName: 159960117927.dkr.ecr.ap-northeast-2.amazonaws.com/
  newTag: 88f00d537ee885ab981126980e3c0a5fe8396aab
- name: 159960117927.dkr.ecr.ap-northeast-2.amazonaws.com/enterwait-dev
  newName: 159960117927.dkr.ecr.ap-northeast-2.amazonaws.com/enterwait-dev
  newTag: be870ca335651f6a9e4da7aef1306a6fd5f9ae36
resources:
- ../../base
patchesStrategicMerge:
- enterwait-deployment-patch.yml
- enterwait-service-patch.yml
