apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 159960117927.dkr.ecr.ap-northeast-2.amazonaws.com/enterwait-dev
  newName: 159960117927.dkr.ecr.ap-northeast-2.amazonaws.com/enterwait-dev
  newTag: 3a7328073c0454a95fe734de47b5676181c37e4f
resources:
- ../../base
patchesStrategicMerge:
- enterwait-deployment-patch.yml
- enterwait-service-patch.yml
